name: artifact-evaluation
run-name: ${{ inputs.task }} / ${{ inputs.optionDisplayName }}
on:
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        options:
          - task_1
          - task_2
      option:
        type: string
        required: true
      optionDisplayName:
        type: string
        required: true
jobs:
  task_1:
    if: ${{ inputs.task == 'task_1' }}
    runs-on: ubuntu-latest
    env:
      OPTION: ${{ inputs.option }}
    steps:
      - uses: actions/checkout@v6
      - name: Run task_1
        run: bash task_1.sh "$OPTION"
  task_2:
    if: ${{ inputs.task == 'task_2' }}
    runs-on: ubuntu-latest
    env:
      OPTION: ${{ inputs.option }}
    steps:
      - uses: actions/checkout@v6
      - name: Run task_2
        run: bash task_2.sh "$OPTION"
